// Code generated by go-swagger; DO NOT EDIT.

package dtos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Healthcheck healthcheck
//
// swagger:model healthcheck
type Healthcheck struct {

	// environment
	// Example: development
	Environment string `json:"environment,omitempty"`

	// status
	// Example: available
	Status string `json:"status,omitempty"`

	// version
	// Example: 1.0.0
	Version string `json:"version,omitempty"`
}

// Validate validates this healthcheck
func (m *Healthcheck) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this healthcheck based on context it is used
func (m *Healthcheck) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Healthcheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Healthcheck) UnmarshalBinary(b []byte) error {
	var res Healthcheck
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
