ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  Status: Available
  RoutePrefix: /api/v1/ecommerce-api
  Debug: 
  Port: 
  TimeoutSecs: 
  ReadTimeoutSecs: 
  WriteTimeoutSecs: 

JWTConfig:
  SessionTime: 
  SecretKey: 

DBConfig:
  DataSourceName: 
  Name: 
  MaxOpen: 
  MaxIdle: 
  MaxLifetime: 